import type { Product, Category, User, Order } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    price: 299.99,
    originalPrice: 399.99,
    image: "/premium-wireless-headphones.png",
    images: ["/premium-wireless-headphones.png", "/premium-wireless-headphones.png"],
    description: "High-quality wireless headphones with noise cancellation and premium sound quality.",
    detailedDescription:
      "Experience superior audio quality with our premium wireless headphones featuring advanced noise cancellation technology, 30-hour battery life, and crystal-clear sound reproduction. Perfect for music lovers and professionals alike.",
    category: "Electronics",
    brand: "AudioTech",
    inStock: true,
    stockCount: 25,
    rating: 4.5,
    reviewCount: 128,
    features: [
      "Active Noise Cancellation",
      "30-hour battery life",
      "Bluetooth 5.0",
      "Quick charge - 5 min for 2 hours",
      "Premium leather ear cups",
    ],
    specifications: {
      "Driver Size": "40mm",
      "Frequency Response": "20Hz - 20kHz",
      Impedance: "32 Ohm",
      Weight: "250g",
      Connectivity: "Bluetooth 5.0, 3.5mm jack",
    },
  },
  {
    id: "2",
    name: "Luxury Watch Collection",
    price: 899.99,
    originalPrice: 1199.99,
    image: "/luxury-watch-elegant-design.jpg",
    images: ["/luxury-watch-elegant-design.jpg"],
    description: "Elegant timepiece with Swiss movement and premium leather strap.",
    detailedDescription:
      "Crafted with precision Swiss movement and featuring a premium leather strap, this luxury watch combines timeless elegance with modern functionality. Water-resistant and built to last a lifetime.",
    category: "Accessories",
    brand: "TimeClassic",
    inStock: true,
    stockCount: 12,
    rating: 4.8,
    reviewCount: 89,
    features: [
      "Swiss Quartz Movement",
      "Sapphire Crystal Glass",
      "Water Resistant 100m",
      "Premium Leather Strap",
      "2-year warranty",
    ],
    specifications: {
      "Case Material": "Stainless Steel",
      "Case Diameter": "42mm",
      "Water Resistance": "100m",
      Movement: "Swiss Quartz",
      "Strap Material": "Genuine Leather",
    },
  },
  // Electronics - Mobiles
  {
    id: "mob-1",
    name: "iPhone 15 Pro Max",
    price: 1199.99,
    originalPrice: 1299.99,
    image: "/iphone-15-pro-max.png",
    images: ["/iphone-15-pro-max-front.png", "/iphone-15-pro-max-back.png"],
    description: "Latest iPhone with A17 Pro chip and titanium design",
    detailedDescription:
      "The iPhone 15 Pro Max features the powerful A17 Pro chip, titanium construction, and advanced camera system with 5x telephoto zoom.",
    category: "Mobiles",
    brand: "Apple",
    inStock: true,
    stockCount: 45,
    rating: 4.8,
    reviewCount: 234,
    features: ["A17 Pro Chip", "Titanium Design", "5x Telephoto Zoom", "Action Button", "USB-C"],
    specifications: {
      Display: "6.7-inch Super Retina XDR",
      Storage: "256GB",
      Camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto",
      Battery: "Up to 29 hours video playback",
      OS: "iOS 17",
    },
  },
  {
    id: "mob-2",
    name: "Samsung Galaxy S24 Ultra",
    price: 1099.99,
    originalPrice: 1199.99,
    image: "/samsung-galaxy-s24-ultra.png",
    description: "Premium Android flagship with S Pen and AI features",
    detailedDescription:
      "Galaxy S24 Ultra combines powerful performance with AI-enhanced photography and the precision of the built-in S Pen.",
    category: "Mobiles",
    brand: "Samsung",
    inStock: true,
    stockCount: 32,
    rating: 4.7,
    reviewCount: 189,
    features: ["Snapdragon 8 Gen 3", "S Pen Built-in", "200MP Camera", "AI Photo Editing", "5000mAh Battery"],
    specifications: {
      Display: "6.8-inch Dynamic AMOLED 2X",
      Storage: "256GB",
      Camera: "200MP Main + 50MP Periscope + 12MP Ultra Wide + 10MP Telephoto",
      Battery: "5000mAh",
      OS: "Android 14",
    },
  },
  {
    id: "mob-3",
    name: "Google Pixel 8 Pro",
    price: 899.99,
    image: "/placeholder-34z3u.png",
    description: "AI-powered photography and pure Android experience",
    detailedDescription:
      "Pixel 8 Pro delivers exceptional computational photography with Google's Tensor G3 chip and pure Android experience.",
    category: "Mobiles",
    brand: "Google",
    inStock: true,
    stockCount: 28,
    rating: 4.6,
    reviewCount: 156,
    features: ["Tensor G3 Chip", "Magic Eraser", "Night Sight", "Pure Android", "7 Years Updates"],
    specifications: {
      Display: "6.7-inch LTPO OLED",
      Storage: "128GB",
      Camera: "50MP Main + 48MP Ultra Wide + 48MP Telephoto",
      Battery: "5050mAh",
      OS: "Android 14",
    },
  },
  {
    id: "mob-4",
    name: "OnePlus 12",
    price: 799.99,
    image: "/placeholder-10omr.png",
    description: "Fast charging flagship with Hasselblad cameras",
    detailedDescription:
      "OnePlus 12 features ultra-fast 100W charging, Hasselblad-tuned cameras, and flagship performance at a competitive price.",
    category: "Mobiles",
    brand: "OnePlus",
    inStock: true,
    stockCount: 41,
    rating: 4.5,
    reviewCount: 203,
    features: ["Snapdragon 8 Gen 3", "100W SuperVOOC", "Hasselblad Cameras", "120Hz Display", "OxygenOS 14"],
    specifications: {
      Display: "6.82-inch AMOLED",
      Storage: "256GB",
      Camera: "50MP Main + 64MP Periscope + 48MP Ultra Wide",
      Battery: "5400mAh",
      OS: "OxygenOS 14",
    },
  },
  {
    id: "mob-5",
    name: "Xiaomi 14 Ultra",
    price: 999.99,
    image: "/placeholder-nrg0r.png",
    description: "Photography flagship with Leica partnership",
    detailedDescription:
      "Xiaomi 14 Ultra combines Leica optics with powerful Snapdragon 8 Gen 3 performance for professional photography.",
    category: "Mobiles",
    brand: "Xiaomi",
    inStock: true,
    stockCount: 19,
    rating: 4.7,
    reviewCount: 87,
    features: ["Leica Cameras", "Snapdragon 8 Gen 3", "90W Fast Charging", "IP68 Rating", "MIUI 15"],
    specifications: {
      Display: "6.73-inch AMOLED",
      Storage: "512GB",
      Camera: "50MP Main + 50MP Ultra Wide + 50MP Periscope + 50MP Telephoto",
      Battery: "5300mAh",
      OS: "MIUI 15",
    },
  },

  // Computers
  {
    id: "comp-1",
    name: "MacBook Pro 16-inch M3 Max",
    price: 2499.99,
    originalPrice: 2699.99,
    image: "/macbook-pro-16-inch-laptop.jpg",
    description: "Professional laptop with M3 Max chip for creative workflows",
    detailedDescription:
      "MacBook Pro 16-inch with M3 Max delivers unprecedented performance for video editing, 3D rendering, and professional workflows.",
    category: "Computers",
    brand: "Apple",
    inStock: true,
    stockCount: 15,
    rating: 4.9,
    reviewCount: 145,
    features: [
      "M3 Max Chip",
      "16-inch Liquid Retina XDR",
      "22-hour Battery",
      "6 Thunderbolt 4 Ports",
      "Studio-quality Mics",
    ],
    specifications: {
      Processor: "Apple M3 Max",
      Memory: "36GB Unified Memory",
      Storage: "1TB SSD",
      Display: "16.2-inch Liquid Retina XDR",
      Graphics: "40-core GPU",
    },
  },
  {
    id: "comp-2",
    name: "Dell XPS 15 OLED",
    price: 1899.99,
    image: "/dell-xps-15-laptop-oled.jpg",
    description: "Premium Windows laptop with stunning OLED display",
    detailedDescription:
      "Dell XPS 15 features a gorgeous 15.6-inch OLED display, Intel Core i7 processor, and premium build quality.",
    category: "Computers",
    brand: "Dell",
    inStock: true,
    stockCount: 23,
    rating: 4.6,
    reviewCount: 198,
    features: ["15.6-inch OLED", "Intel Core i7-13700H", "RTX 4060", "32GB RAM", "1TB SSD"],
    specifications: {
      Processor: "Intel Core i7-13700H",
      Memory: "32GB DDR5",
      Storage: "1TB PCIe SSD",
      Display: "15.6-inch OLED 3.5K",
      Graphics: "NVIDIA RTX 4060",
    },
  },
  {
    id: "comp-3",
    name: "ASUS ROG Zephyrus G16",
    price: 2199.99,
    image: "/asus-rog-gaming-laptop.jpg",
    description: "High-performance gaming laptop with RTX 4070",
    detailedDescription:
      "ROG Zephyrus G16 combines powerful gaming performance with a sleek design, perfect for gaming and content creation.",
    category: "Computers",
    brand: "ASUS",
    inStock: true,
    stockCount: 18,
    rating: 4.7,
    reviewCount: 167,
    features: ["AMD Ryzen 9 7940HS", "RTX 4070", "240Hz Display", "32GB RAM", "ROG Intelligent Cooling"],
    specifications: {
      Processor: "AMD Ryzen 9 7940HS",
      Memory: "32GB DDR5",
      Storage: "1TB PCIe 4.0 SSD",
      Display: "16-inch QHD+ 240Hz",
      Graphics: "NVIDIA RTX 4070",
    },
  },
  {
    id: "comp-4",
    name: "Microsoft Surface Laptop Studio 2",
    price: 1999.99,
    image: "/microsoft-surface-laptop-studio-convertible.jpg",
    description: "Versatile 2-in-1 laptop for creative professionals",
    detailedDescription:
      "Surface Laptop Studio 2 transforms from laptop to studio canvas, perfect for designers and creative professionals.",
    category: "Computers",
    brand: "Microsoft",
    inStock: true,
    stockCount: 12,
    rating: 4.5,
    reviewCount: 89,
    features: ["Intel Core i7-13700H", "RTX 4050", "Touchscreen", "Surface Pen Support", "Versatile Design"],
    specifications: {
      Processor: "Intel Core i7-13700H",
      Memory: "32GB LPDDR5x",
      Storage: "1TB SSD",
      Display: "14.4-inch PixelSense Flow",
      Graphics: "NVIDIA RTX 4050",
    },
  },

  // TV & Appliances
  {
    id: "tv-1",
    name: 'Samsung 65" Neo QLED 8K',
    price: 2799.99,
    originalPrice: 3299.99,
    image: "/samsung-neo-qled-8k-tv.jpg",
    description: "Premium 8K TV with Quantum Matrix Technology",
    detailedDescription:
      "Experience stunning 8K resolution with Quantum Matrix Technology and Neural Quantum Processor for upscaling.",
    category: "TV & Appliances",
    brand: "Samsung",
    inStock: true,
    stockCount: 8,
    rating: 4.8,
    reviewCount: 156,
    features: [
      "8K Resolution",
      "Quantum Matrix Technology",
      "Neural Quantum Processor",
      "Object Tracking Sound+",
      "Gaming Hub",
    ],
    specifications: {
      "Screen Size": "65 inches",
      Resolution: "7680 x 4320 (8K)",
      HDR: "HDR10+, HLG",
      "Refresh Rate": "120Hz",
      "Smart TV": "Tizen OS",
    },
  },
  {
    id: "tv-2",
    name: 'LG 77" OLED C3',
    price: 2299.99,
    image: "/lg-oled-c3-tv.jpg",
    description: "Self-lit OLED TV with perfect blacks and infinite contrast",
    detailedDescription:
      "LG OLED C3 delivers perfect blacks and infinite contrast with self-lit pixels and α9 Gen6 AI Processor.",
    category: "TV & Appliances",
    brand: "LG",
    inStock: true,
    stockCount: 11,
    rating: 4.9,
    reviewCount: 203,
    features: ["Self-Lit OLED", "α9 Gen6 AI Processor", "Dolby Vision IQ", "120Hz Gaming", "webOS 23"],
    specifications: {
      "Screen Size": "77 inches",
      Resolution: "3840 x 2160 (4K)",
      HDR: "Dolby Vision IQ, HDR10, HLG",
      "Refresh Rate": "120Hz",
      "Smart TV": "webOS 23",
    },
  },

  // Men's Fashion
  {
    id: "mens-1",
    name: "Premium Leather Jacket",
    price: 299.99,
    originalPrice: 399.99,
    image: "/premium-leather-jacket-men.jpg",
    description: "Genuine leather jacket with classic design",
    detailedDescription:
      "Crafted from premium genuine leather, this jacket combines timeless style with modern comfort and durability.",
    category: "Men's Fashion",
    brand: "StyleCraft",
    inStock: true,
    stockCount: 25,
    rating: 4.6,
    reviewCount: 134,
    features: ["Genuine Leather", "YKK Zippers", "Quilted Lining", "Multiple Pockets", "Classic Fit"],
    specifications: {
      Material: "100% Genuine Leather",
      Lining: "Quilted Polyester",
      Closure: "YKK Zipper",
      Care: "Professional Leather Cleaning",
      Sizes: "S, M, L, XL, XXL",
    },
  },
  {
    id: "mens-2",
    name: "Casual Cotton Shirt",
    price: 79.99,
    image: "/casual-cotton-shirt-men.jpg",
    description: "Comfortable cotton shirt for everyday wear",
    detailedDescription: "Soft cotton shirt with modern fit, perfect for casual occasions and everyday comfort.",
    category: "Men's Fashion",
    brand: "ComfortWear",
    inStock: true,
    stockCount: 67,
    rating: 4.4,
    reviewCount: 89,
    features: ["100% Cotton", "Modern Fit", "Wrinkle Resistant", "Button-down Collar", "Machine Washable"],
    specifications: {
      Material: "100% Cotton",
      Fit: "Modern",
      Collar: "Button-down",
      Care: "Machine Washable",
      Sizes: "S, M, L, XL, XXL",
    },
  },

  // Women's Fashion
  {
    id: "womens-1",
    name: "Elegant Evening Dress",
    price: 199.99,
    originalPrice: 249.99,
    image: "/elegant-evening-dress-women.jpg",
    description: "Sophisticated evening dress for special occasions",
    detailedDescription:
      "Beautifully designed evening dress with flowing silhouette and premium fabric, perfect for formal events.",
    category: "Women's Fashion",
    brand: "EleganceWear",
    inStock: true,
    stockCount: 18,
    rating: 4.7,
    reviewCount: 76,
    features: ["Premium Fabric", "Flowing Silhouette", "Hidden Zipper", "Lined Interior", "Dry Clean Only"],
    specifications: {
      Material: "Polyester Blend",
      Length: "Midi",
      Closure: "Hidden Zipper",
      Care: "Dry Clean Only",
      Sizes: "XS, S, M, L, XL",
    },
  },
  {
    id: "womens-2",
    name: "Designer Handbag",
    price: 149.99,
    image: "/designer-handbag-women.jpg",
    description: "Stylish handbag with premium materials",
    detailedDescription:
      "Crafted with attention to detail, this handbag combines style and functionality for the modern woman.",
    category: "Women's Fashion",
    brand: "LuxeStyle",
    inStock: true,
    stockCount: 34,
    rating: 4.5,
    reviewCount: 112,
    features: ["Premium Materials", "Multiple Compartments", "Adjustable Strap", "Gold Hardware", "Dust Bag Included"],
    specifications: {
      Material: "Synthetic Leather",
      Dimensions: '12" x 8" x 4"',
      Strap: "Adjustable",
      Hardware: "Gold-tone",
      Interior: "Fabric Lining",
    },
  },

  // Kitchen
  {
    id: "kitchen-1",
    name: "Professional Stand Mixer",
    price: 399.99,
    originalPrice: 499.99,
    image: "/professional-stand-mixer-kitchen.jpg",
    description: "Heavy-duty stand mixer for baking enthusiasts",
    detailedDescription:
      "Professional-grade stand mixer with powerful motor and multiple attachments for all your baking needs.",
    category: "Kitchen",
    brand: "ChefMaster",
    inStock: true,
    stockCount: 22,
    rating: 4.8,
    reviewCount: 187,
    features: ["800W Motor", "6-Quart Bowl", "10 Speeds", "Tilt-Head Design", "Multiple Attachments"],
    specifications: {
      Power: "800 Watts",
      "Bowl Capacity": "6 Quarts",
      Speeds: "10",
      Material: "Die-cast Metal",
      Warranty: "2 Years",
    },
  },
  {
    id: "kitchen-2",
    name: "Smart Coffee Maker",
    price: 249.99,
    image: "/smart-coffee-maker.jpg",
    description: "WiFi-enabled coffee maker with app control",
    detailedDescription:
      "Smart coffee maker that you can control from your phone, with programmable brewing and temperature control.",
    category: "Kitchen",
    brand: "BrewTech",
    inStock: true,
    stockCount: 31,
    rating: 4.6,
    reviewCount: 143,
    features: ["WiFi Connectivity", "App Control", "Programmable", "Temperature Control", "Auto Shut-off"],
    specifications: {
      Capacity: "12 Cups",
      Connectivity: "WiFi",
      Material: "Stainless Steel",
      Features: "Programmable, Auto Shut-off",
      Warranty: "1 Year",
    },
  },

  // Home Decor
  {
    id: "home-1",
    name: "Modern Floor Lamp",
    price: 179.99,
    image: "/modern-floor-lamp-home-decor.jpg",
    description: "Contemporary floor lamp with adjustable brightness",
    detailedDescription:
      "Sleek modern floor lamp with LED lighting and adjustable brightness settings to complement any room.",
    category: "Home Decor",
    brand: "LightCraft",
    inStock: true,
    stockCount: 45,
    rating: 4.5,
    reviewCount: 98,
    features: ["LED Lighting", "Adjustable Brightness", "Modern Design", "Energy Efficient", "Easy Assembly"],
    specifications: {
      Height: "60 inches",
      "Light Type": "LED",
      Power: "15W",
      Material: "Metal and Fabric",
      Warranty: "1 Year",
    },
  },
  {
    id: "home-2",
    name: "Decorative Wall Art Set",
    price: 89.99,
    image: "/decorative-wall-art-set.jpg",
    description: "Set of 3 canvas prints for modern home decor",
    detailedDescription:
      "Beautiful set of three canvas prints featuring abstract designs, perfect for adding style to any room.",
    category: "Home Decor",
    brand: "ArtVision",
    inStock: true,
    stockCount: 52,
    rating: 4.4,
    reviewCount: 67,
    features: ["Set of 3", "Canvas Material", "Ready to Hang", "Fade Resistant", "Modern Abstract Design"],
    specifications: {
      Size: '16" x 20" each',
      Material: "Canvas",
      Frame: "Not Included",
      Mounting: "Ready to Hang",
      Style: "Modern Abstract",
    },
  },
]

export const categories: Category[] = [
  { id: "1", name: "Mobiles", slug: "mobiles", icon: "📱", image: "/iphone-15-pro-max.png", productCount: 5 },
  { id: "2", name: "Computers", slug: "computers", icon: "💻", image: "/macbook-pro-16-inch-laptop.jpg", productCount: 4 },
  { id: "3", name: "TV & Appliances", slug: "tv-appliances", icon: "📺", image: "/samsung-neo-qled-8k-tv.jpg", productCount: 2 },
  { id: "4", name: "Electronics", slug: "electronics", icon: "🔌", image: "/premium-wireless-headphones.png", productCount: 0 },
  { id: "5", name: "Men's Fashion", slug: "mens-fashion", icon: "👔", image: "/premium-leather-jacket-men.jpg", productCount: 2 },
  { id: "6", name: "Women's Fashion", slug: "womens-fashion", icon: "👗", image: "/elegant-evening-dress-women.jpg", productCount: 2 },
  { id: "7", name: "Kitchen", slug: "kitchen", icon: "🍳", image: "/professional-stand-mixer-kitchen.jpg", productCount: 2 },
  { id: "8", name: "Home Decor", slug: "home-decor", icon: "🏠", image: "/modern-floor-lamp-home-decor.jpg", productCount: 2 },
]

export const mockUser: User = {
  id: "user-1",
  name: "John Doe",
  email: "john.doe@example.com",
  avatar: "/diverse-user-avatars.png",
  joinedDate: new Date("2023-01-15"),
}

export const mockOrders: Order[] = [
  {
    id: "order-1",
    orderNumber: "CK-2024-001",
    items: [
      { product: mockProducts[0], quantity: 1 },
      { product: mockProducts[1], quantity: 1 },
    ],
    totalAmount: 1199.98,
    status: "delivered",
    createdAt: new Date("2024-01-15"),
    estimatedDelivery: new Date("2024-01-20"),
  },
  {
    id: "order-2",
    orderNumber: "CK-2024-002",
    items: [{ product: mockProducts[4], quantity: 1 }],
    totalAmount: 399.99,
    status: "shipped",
    createdAt: new Date("2024-02-01"),
    estimatedDelivery: new Date("2024-02-05"),
  },
]
export const mockDeals = [
  {
    id: "deal-1",
    title: "New Year Sale 2025",
    description: "Up to 50% off on selected items",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    discountType: "percentage",
    discountValue: 50,
    image: "/placeholder.svg",
  },
  {
    id: "deal-2",
    title: "Christmas Sale",
    description: "Amazing holiday deals on electronics and gifts",
    startDate: new Date("2024-12-20"),
    endDate: new Date("2024-12-26"),
    discountType: "percentage",
    discountValue: 40,
    image: "/placeholder.svg",
  },
  {
    id: "deal-3",
    title: "Diwali Sale",
    description: "Festival special - Save big on home and lifestyle",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-15"),
    discountType: "percentage",
    discountValue: 45,
    image: "/placeholder.svg",
  },
  {
    id: "deal-4",
    title: "Mega Flash Sale",
    description: "Limited time offers on best sellers",
    startDate: new Date("2024-12-25"),
    endDate: new Date("2024-12-31"),
    discountType: "percentage",
    discountValue: 60,
    image: "/placeholder.svg",
  },
]

export const topDeals = mockProducts.filter(p => p.originalPrice && (p.originalPrice - p.price) / p.originalPrice > 0.2).slice(0, 6)
export const cheapProducts = mockProducts.filter(p => p.price < 200).slice(0, 6)